#!/usr/bin/env python3
"""Aggregate LIBERO planning-only runs into paper-facing tables."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
METHOD_ORDER = [
    "direct_bt",
    "actionseq",
    "concept_raw",
    "concept_nostable",
    "concept_ruleonly",
    "concept_shuffle",
    "concept_random",
    "concept",
    "oracle_pyramid",
]


def find_latest_run(runs_dir: Path) -> Path:
    candidates = sorted(p for p in runs_dir.glob("*__libero_planning_only") if (p / "summary.json").is_file())
    if not candidates:
        raise SystemExit(f"No planning-only runs found under {runs_dir}")
    return candidates[-1]


def read_summary(run_dir: Path) -> dict[str, Any]:
    return json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))


def method_rows(summary: dict[str, Any]) -> list[dict[str, Any]]:
    by_method = summary["by_method"]
    rows = []
    for method in METHOD_ORDER:
        if method in by_method:
            row = {"method": method, **by_method[method]}
            rows.append(row)
    for method, values in sorted(by_method.items()):
        if method not in METHOD_ORDER:
            rows.append({"method": method, **values})
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fields = ["method", "n", "exec", "lc", "symbolic_sr", "avg_bt_nodes", "avg_stable_subgoals", "avg_plan_ms"]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row[field] for field in fields})


def write_markdown(path: Path, run_dir: Path, summary: dict[str, Any], rows: list[dict[str, Any]]) -> None:
    lines = [
        "# LIBERO Planning-Only Aggregation",
        "",
        f"Source run: `{run_dir.name}`",
        "",
        "Scope: symbolic planning-only checker over extracted LIBERO BDDL goals. These are not low-level MuJoCo/VLA rollout success rates.",
        "",
        "| Method | N | Exec | LC | Symbolic SR | Nodes | Stable SG | Plan ms |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| {row['method']} | {row['n']} | {row['exec']} | {row['lc']} | {row['symbolic_sr']} | "
            f"{row['avg_bt_nodes']:.2f} | {row['avg_stable_subgoals']:.2f} | {row['avg_plan_ms']:.3f} |"
        )
    lines.extend(
        [
            "",
            "## Suite Breakdown",
            "",
            "| Suite / Method | N | Exec | LC | Symbolic SR |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for key, row in sorted(summary["by_suite_method"].items()):
        lines.append(f"| {key} | {row['n']} | {row['exec']} | {row['lc']} | {row['symbolic_sr']} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_latex(path: Path, run_dir: Path, rows: list[dict[str, Any]]) -> None:
    lines = [
        "% Auto-generated by analysis/aggregate_libero_planning_only.py",
        f"% Source run: {run_dir.name}",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "Method & N & Exec & LC & Symbolic SR & Nodes & Stable SG \\\\",
        "\\midrule",
    ]
    for row in rows:
        method_name = row["method"].replace("_", "\\_")
        lines.append(
            f"{method_name} & {row['n']} & {row['exec']} & {row['lc']} & "
            f"{row['symbolic_sr']} & {row['avg_bt_nodes']:.2f} & {row['avg_stable_subgoals']:.2f} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", default=None)
    parser.add_argument("--output-prefix", default="analysis/libero_planning_only_latest")
    args = parser.parse_args()

    run_dir = Path(args.run_dir).resolve() if args.run_dir else find_latest_run(PROJECT_ROOT / "runs")
    summary = read_summary(run_dir)
    rows = method_rows(summary)
    output_prefix = PROJECT_ROOT / args.output_prefix

    write_csv(output_prefix.with_suffix(".csv"), rows)
    write_markdown(output_prefix.with_suffix(".md"), run_dir, summary, rows)
    write_latex(output_prefix.with_suffix(".tex"), run_dir, rows)
    print(json.dumps({"run_dir": str(run_dir), "outputs": [str(output_prefix.with_suffix(ext)) for ext in [".csv", ".md", ".tex"]]}, indent=2))


if __name__ == "__main__":
    main()
